
# [general]
general:
  dataset: nips4b

# [classifier settings]
classifier:
  save_model: True
  test_size: 0.2
  shuffle: True
  random_state: 0
  verbose: 0
  scoring: f1

random_forest:
  n_estimators: 500
  criterion: entropy
  max_depth: 8
  min_samples_leaf: 8
  n_jobs: -1

svm:
  kernel: linear
  degree: 2 
  gamma: auto
  probability: True
  max_iter: -1

# [preprocessing]
activity_detector:
  window_length: 0.1
  window_overlap: 0.05
  block: 0.25
  threshold: 0.35
  band_start: 800
  band_end: 16000

noise_reduce:
  window_length: 0.1
  overlap: 0.05
  nth_oct: 6
  norm_freq: 2000
  start_band: -4
  end_band: 15
  r_filters: 3

band_filter:
  filt_min_freq: 800
  filt_max_freq: 16000

# Features
AM:
  min_mod: 1.0
  max_mod: 8.0
  prominence_cutoff: 3.0
  depth_threshold: 0.01

FM:
  window_length: 0.02
  window_overlap: 0.01
  threshold: 0.2