# [general]
general:
  dataset: nips4b

# [classifier settings]
classifier:
  type: rf
  save_model: True
  test_size: 0.2
  shuffle: True
  random_state: 0
  verbose: 0
  grid_search: False
  scoring: precision

random_forest:
  n_estimators: 200
  criterion: gini
  max_depth: 8
  min_samples_leaf: 4
  n_jobs: 8

svm:
  kernel: rbf
  degree: 2 
  gamma: scale
  probability: True
  max_iter: 2000

xgb:
  booster: gbtree
  gamma: 1
  colsample_bytree: 1
  subsample: 0.1
  min_child_weight: 1
  lr: 0.02
  max_depth: 5
  n_estimators: 500
  eval_metric: logloss
  scale_pos_weight: 1.8

# [preprocessing]
activity_detector:
  window_length: 0.1
  window_overlap: 0.05
  block: 0.5
  threshold: 0.35
  band_start: 800
  band_end: 10000

noise_reduce:
  window_length: 0.25
  overlap: 0.125
  nth_oct: 6
  norm_freq: 2000
  start_band: -4
  end_band: 15
  r_filters: 3

band_filter:
  filt_min_freq: 800
  filt_max_freq: 10000

# Features
AM:
  min_mod: 1
  max_mod: 10
  prominence_cutoff: 5

FM:
  window_length: 0.02
  window_overlap: 0.01
  threshold: 0.3