# [general]
general:
  dataset: nips4b

# [classifier settings]
classifier:
  type: xgb
  save_model: True
  test_size: 0.2
  shuffle: True
  random_state: 0
  verbose: 1
  grid_search: False
  scoring: accuracy

random_forest:
  n_estimators: 100
  criterion: gini
  max_depth: 4
  min_samples_leaf: 16
  n_jobs: 8

svm:
  kernel: linear
  degree: 2 
  gamma: auto
  probability: True
  max_iter: 100

xgb:
  booster: gbtree
  gamma: 1
  colsample_bytree: 1
  subsample: 1
  min_child_weight: 2
  lr: 0.02
  max_depth: 5
  n_estimators: 500
  eval_metric: logloss
  scale_pos_weight: 1.8

# [preprocessing]
activity_detector:
  window_length: 0.02
  window_overlap: 0.01
  block: 0.2
  threshold: 0.33

noise_reduce:
  window_length: 0.25
  overlap: 0.125
  nth_oct: 6
  norm_freq: 2000
  start_band: -4
  end_band: 15
  r_filters: 3

band_filter:
  filt_min_freq: 800
  filt_max_freq: 10000

# Features
AM:
  min_mod: 1
  max_mod: 10
  prominence_cutoff: 4

FM:
  window_length: 0.02
  window_overlap: 0.01
  threshold: 0.3